### ISSUE TITLE
v1.0.0-alpha.50 doesn't work

### ISSUE THREAD

**Issue by LordGhostX** [acid-info/logos-docusaurus-plugins#70]
I tried upgrading the `logos-docusaurus-preset` package to `v1.0.0-alpha.50` and I got this error:

```bash
yarn run v1.22.19
warning ../../package.json: No license field
$ docusaurus start
[INFO] Starting the development server...
[ERROR] Error: Plugin "docusaurus-theme-mermaid" is used 2 times with ID "default".
To use the same plugin multiple times on a Docusaurus site, you need to assign a unique ID to each plugin instance.

The plugin ID is "default" by default. It's possible that the preset you are using already includes a plugin instance, in which case you either want to disable the plugin in the preset (to use a single instance), or assign another ID to your extra plugin instance (to use multiple instances).
    at /Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:23:23
    at Array.forEach (<anonymous>)
    at /Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:21:45
    at Array.forEach (<anonymous>)
    at ensureUniquePluginInstanceIds (/Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/plugins/pluginIds.js:19:35)
    at initPlugins (/Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/plugins/init.js:92:51)
    at async loadPlugins (/Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/plugins/index.js:26:21)
    at async load (/Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/server/index.js:76:58)
    at async Command.start (/Users/lordghostx/Desktop/docs.waku.org/node_modules/@docusaurus/core/lib/commands/start.js:44:19)
[INFO] Docusaurus version: 2.4.1
Node version: v20.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I've tried lower versions too (40 - 49), and I got the same error.

**Comment by LordGhostX** [comment]
Thanks, it works now 🥳
